apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: sbonilla284/app1:3.8
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
        startupProbe:
          httpGet:
            path: /api/
            port: 8080
          initialDelaySeconds: 35
          periodSeconds: 10         # Reintenta cada 5s
          failureThreshold: 6        # Falla después de 6 intentos
        env:
          - name: DB_URL
            value: "jdbc:postgresql://postgres-service.db.svc.cluster.local:5432/bdnames"
          - name: DB_USERNAME
            value: "names"
          - name: DB_PASSWORD
            value: "names"